services:
  infrastructure-gateway:
    image: registry.token-ai.cn/earth-chat/infrastructure-gateway
    build:
      context: .
      dockerfile: src/gateway/EarthChat.Infrastructure.Gateway/Dockerfile


  earthchat.authserver:
    image: earthchat.authserver
    build:
      context: .
      dockerfile: src/auth/EarthChat.AuthServer/Dockerfile
