services:
  postgres:
    image: postgres:15.3-alpine3.18
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    networks:
      - chat
    environment:
      POSTGRES_USER: token
      POSTGRES_PASSWORD: dd666666
      POSTGRES_DB: Chat
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine3.16
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - chat
    command: redis-server --appendonly yes
    volumes:
      - ./redisdata:/data

  nginx:
    image: nginx:stable-alpine
    restart: always
    container_name: nginx
    networks:
      - chat
    ports:
      - 1080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  chat-web:
    build:
      context: ./web
      dockerfile: ./Dockerfile
    container_name: chat-web
    image: registry.cn-shenzhen.aliyuncs.com/gotrays/chat-web
    restart: always
    volumes:
      - ./node_modules:/src/node_modules
    depends_on:
     - redis
     - postgres
    networks:
      - chat

  chat-api:
    build:
      context: ./
      dockerfile: ./src/Chat.Service/Dockerfile
    container_name: chat-api
    image: registry.cn-shenzhen.aliyuncs.com/gotrays/chat-api
    restart: always
    depends_on:
     - redis
     - postgres
    networks:
      - chat

networks:
  chat:
    driver: bridge