name: master
on:
  push:
    branches:
      - master 
    paths: 
      - 'Directory.Build.props'
      - '.github/workflows/dotnet.yml'
  
jobs:
  deploy-nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .Net SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore Dependencies
        run: dotnet restore -c Release 

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Pack
        run: dotnet pack --no-build -c Release 

      - name: Push NuGet package
        run: |
          dotnet nuget push **/*.nupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET }}
        env:
          NUGET_API_KEY: ${{ secrets.NUGET }}
